# Generated by Django 4.1.3 on 2022-11-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("s_name", models.CharField(max_length=16)),
                ("s_password", models.CharField(max_length=128)),
                ("s_sex", models.CharField(default="男", max_length=2)),
                ("s_age", models.IntegerField(default=15)),
                ("s_phone", models.CharField(default="新华中学", max_length=20)),
                ("s_token", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("u_name", models.CharField(max_length=16)),
                ("u_icon", models.ImageField(upload_to="icons")),
            ],
        ),
    ]
