# Generated by Django 4.1.3 on 2022-11-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AfterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("after_icon", models.ImageField(upload_to="after_icons")),
                ("message", models.TextField()),
            ],
        ),
        migrations.DeleteModel(name="UserModel",),
        migrations.AddField(
            model_name="student",
            name="s_icon",
            field=models.ImageField(default=None, upload_to="icons"),
        ),
        migrations.AddField(
            model_name="aftermodel",
            name="after_name",
            field=models.ManyToManyField(to="App.student"),
        ),
    ]
