# Generated by Django 4.1.3 on 2022-11-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_aftermodel_delete_usermodel_student_s_icon_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("u_name", models.CharField(max_length=16)),
                ("u_icon", models.ImageField(default=None, upload_to="icons")),
                (
                    "after_uicon",
                    models.ImageField(default=None, upload_to="after_icons"),
                ),
                ("message", models.TextField(default=None)),
            ],
        ),
        migrations.RemoveField(model_name="student", name="s_icon",),
        migrations.DeleteModel(name="AfterModel",),
        migrations.AddField(
            model_name="usermodel",
            name="u_student",
            field=models.ManyToManyField(to="App.student"),
        ),
    ]
