# Generated by Django 4.1.3 on 2022-11-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0003_usermodel_remove_student_s_icon_delete_aftermodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="message",
            field=models.TextField(default=None, null=True),
        ),
    ]
