# Generated by Django 4.1.3 on 2022-11-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0004_alter_usermodel_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="after_uicon",
            field=models.ImageField(
                default=None, upload_to="<django.db.models.fields.CharField>after_icons"
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="u_icon",
            field=models.ImageField(
                default=None, upload_to="<django.db.models.fields.CharField>icons"
            ),
        ),
    ]
