# Generated by Django 3.2.15 on 2022-11-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20221123_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='after_uicon',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
