# Generated by Django 3.2.15 on 2022-12-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_usermodel_after_uicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recycle_Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=16)),
                ('r_icon', models.ImageField(default=None, upload_to='')),
                ('r_after_uicon', models.ImageField(default=None, upload_to='')),
                ('r_message', models.TextField(default=None)),
                ('r_date', models.DateTimeField(auto_now=True, verbose_name='进入垃圾箱时间')),
                ('r_student', models.ManyToManyField(to='App.Student')),
            ],
        ),
    ]
