# Generated by Django 3.2.15 on 2022-12-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_recycle_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='u_date',
            field=models.DateTimeField(auto_now=True, verbose_name='图片传入时间'),
        ),
    ]
