# Generated by Django 3.2.15 on 2024-07-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_usermodel_u_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_phone',
            field=models.CharField(default='123', max_length=20),
        ),
    ]
